set_property PACKAGE_PIN W5 [get_ports clk] 
    set_property IOSTANDARD LVCMOS33 [get_ports clk] 
    create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

set_property PACKAGE_PIN E19 [get_ports {is_entered}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {is_entered}] 
set_property PACKAGE_PIN U16 [get_ports {is_k_reset}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {is_k_reset}] 
       
set_property PACKAGE_PIN W19 [get_ports shift] 
    set_property IOSTANDARD LVCMOS33 [get_ports shift]
set_property PACKAGE_PIN U18 [get_ports enter] 
    set_property IOSTANDARD LVCMOS33 [get_ports enter] 
set_property PACKAGE_PIN T17 [get_ports resett] 
    set_property IOSTANDARD LVCMOS33 [get_ports resett] 
    
set_property PACKAGE_PIN J3 [get_ports {JA[7]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {JA[7]}]
set_property PACKAGE_PIN L3 [get_ports {JA[6]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {JA[6]}]
set_property PACKAGE_PIN M2 [get_ports {JA[5]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {JA[5]}]
set_property PACKAGE_PIN N2 [get_ports {JA[4]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {JA[4]}]
set_property PACKAGE_PIN K3 [get_ports {JA[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {JA[3]}]
set_property PACKAGE_PIN M3 [get_ports {JA[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {JA[2]}]
set_property PACKAGE_PIN M1 [get_ports {JA[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {JA[1]}]
set_property PACKAGE_PIN N1 [get_ports {JA[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {JA[0]}]

set_property PACKAGE_PIN M18 [get_ports {echo}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {echo}]
set_property PACKAGE_PIN M19 [get_ports {trigger}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {trigger}]
set_property PACKAGE_PIN N17 [get_ports {is_locked}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {is_locked}]
    

set_property PACKAGE_PIN A14 [get_ports {sensor}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {sensor}]    
set_property PACKAGE_PIN P18 [get_ports {Q}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {Q}]
set_property PACKAGE_PIN R18 [get_ports {Q_not}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {Q_not}]
set_property PACKAGE_PIN A16 [get_ports {is_enabled}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {is_enabled}]
        
set_property PACKAGE_PIN V17 [get_ports {enable}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {enable}]     
set_property PACKAGE_PIN R2 [get_ports {ssd_select[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {ssd_select[1]}] 
set_property PACKAGE_PIN T1 [get_ports {ssd_select[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {ssd_select[0]}]
 
        
set_property PACKAGE_PIN U2 [get_ports {an[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}] 
set_property PACKAGE_PIN U4 [get_ports {an[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}] 
set_property PACKAGE_PIN V4 [get_ports {an[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}] 
set_property PACKAGE_PIN W4 [get_ports {an[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
    
set_property PACKAGE_PIN W7 [get_ports {seg[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}] 
set_property PACKAGE_PIN W6 [get_ports {seg[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}] 
set_property PACKAGE_PIN U8 [get_ports {seg[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}] 
set_property PACKAGE_PIN V8 [get_ports {seg[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}] 
set_property PACKAGE_PIN U5 [get_ports {seg[4]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}] 
set_property PACKAGE_PIN V5 [get_ports {seg[5]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}] 
set_property PACKAGE_PIN U7 [get_ports {seg[6]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}] 